research/face_login/urls.py
from django.urls import path
from . import views

app_name = 'face_login'
urlpatterns = [
    path('top/', views.MainPage.as_view(), name="top"),
    path('status/', views.UserStatusView.as_view(), name='status'),
    path("login/", views.LoginFormView.as_view(), name="login"),
    path("list/", views.UserListView.as_view(), name="list"),
    path('detail/<int:pk>', views.UserDetailView.as_view()),
    path("create/", views.UserCreateView.as_view(), name = "create"),
    path("update/<int:pk>", views.UserUpdateView.as_view(), name = "update"),
]

research/research/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path('face/', include('face.urls')),
    path('admin/', admin.site.urls),
    # path('face_AuthC/', include('face_AuthC.urls')),
    path('login/', include("face_login.urls")),
]

research/face_login/models.py
from django.db import models
from django.utils import timezone
import datetime

"""
class テーブル名(model):
    カラム名1 = データ型(その他の制約)
    カラム名2 = データ型(その他の制約)

"""

class person(models.Model):
    #id
    user_id  = models.CharField(max_length=128, verbose_name="ID")
    #名前
    user_name = models.CharField(max_length=128, verbose_name="名前")
    #ログイン時間
    login_time = models.ForeignKey('login_data', blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.user_id


# Create your models here.
class login_data(models.Model):
    in_out = (
        (1, 'in'),
        (0, 'out'),
    )

    user = models.ForeignKey('person', blank=True, null=True, on_delete=models.PROTECT)
    time= models.DateTimeField(default=datetime.datetime.now(), verbose_name="ログイン時間")
    status = models.IntegerField(choices=in_out, default=0, verbose_name="inout")

    def __str__(self):
        return str(self.user) + str(self.time) + str(self.status)

research/face_login/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse, reverse_lazy


import os
from .app import authc
from .form import TestForm, CreateUserForm, LoginForm
from .models import login_data, person
#from .models import person, login_data

class MainPage(generic.ListView):
    """
    login history
    できればメインページとは違うところへ
    """
    template_name = "face_login/index.html"
    context_object_name = "login_data"

    def get_queryset(self):
        return login_data.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)    #super:親クラス(ここではTemplateView)のメソッドを実行
        context["welcome"] = "1"
        return context

class UserDetailView(generic.DetailView):
    model = person
    template_name = "face_login/person_detail.html"

class UserListView(generic.ListView):
    template_name = "face_login/list.html"
    model = person
    context_object_name = "member_list"

class UserCreateView(generic.CreateView):
    model = person
    form_class = CreateUserForm
    template_name = "face_login/create.html"
    success_url = reverse_lazy("face_login:top")

class UserUpdateView(generic.UpdateView):
    template_name = "face_login/create.html"
    model = person
    form_class = CreateUserForm
    success_url = reverse_lazy("face_login:list")

    # def form_valid(self, form):
    #     post = form.save(commit=False)
    #     post.updated_by = self.request.user
    #     post.updated_by =

class LoginFormView(generic.ListView):
    template_name = "face_login/login.html"
    model = person
    form_class = LoginForm
    context_object_name = "member_list"
    #success_url = reverse_lazy("face_login:list")

    # def form_valid(self, form):
    #     if "1" in form.name:
    #         print("OK2")
    #     print("OK")
    #     return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        if "1" in request.POST:
            print("OK2")
            authc.prepare_anthentication()
        if "2" in request.POST:
            print("OK3")
            authc.learning()
        if "3" in request.POST:
            authc.file_Authentication("test1")
            authc.file_Authentication("test2")
            authc.file_Authentication("test3")
            authc.file_Authentication("gakko")
        return render(request, "face_login/login.html")


class UserStatusView(generic.ListView):
    """

    """
    template_name = "face_login/status.html"
    model = person
    form_class = LoginForm
    context_object_name = "member_list"

    def post(self, request, *args, **kwargs):
        #hito = person.objects.get(id=request.POST.get())
        hito = request.POST["LOGIN"]
        user_login_status = person.objects.all().order_by(hito)
        print(user_login_status.login_time)
        return render(request, "face_login/index.html")



# class LoginView(generic.FormView):
#     template_name = "face_login/login.html"
#     model = person
#     context_object_name = "member_list"

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)    #super:親クラス(ここではTemplateView)のメソッドを実行
#         context["result"] = "0"
#         return context

#     def post(self, request):
#         print("post")
#         if "1" in request.POST:
#             # context["result"] = "1"
#         return context

    # def get(self, request, *args):
    #     return render(request, self.template_name)



# def index(request):
#     index_dict = {
#         "welcome" : "1"
#     }
#     return render(request, "face_login/index.html", index_dict)

def login(request):
    login_dict = {
        "form" : TestForm(),
        "result_id" : "0",
        "result": "失敗",

    }

    if request.method == "POST":
        if "authc_button" in request.POST:
            login_dict["result_id"] = authc.authentication()
            if request.POST['id'] == login_dict["result_id"]:
                login_dict["result"] = "成功"
            else:
                login_dict["result"] = "失敗"


    return render(request, "face_login/login.html", login_dict)

research/face_login/templates/face_login/base.html
{% load static %}
<!doctype html>

<html lang = "ja">
    <head>
        <meta charset="utf-8">
        <title>{% block title %} SITE {% endblock　%}</title>
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

    <header class="header-5">
        <div class="header-inner">
          <div class="logo">
            <img src="" />
          </div>
          <nav class="header-nav">
            <ul class="header-nav-list">
              <a href="{% url 'face_login:top' %}"><li class="header-nav-item select">Log</li></a>
              <a href="{% url 'face_login:list' %}"><li class="header-nav-item">List</li></a>
              <a href="{% url 'face_login:login' %}"><li class="header-nav-item">Login</li></a>
              <a href="{% url 'face_login:create'%}"><li class="header-nav-item">New User</li></a>
            </ul>
            <div class="header-ham">
              <div class="menu2"></div>
              <div class="menu2"></div>
              <div class="menu2"></div>
            </div>
          </nav>
        </div>
    </header>

    <body>
        <!-- <div class ="header">
            <a href="{% url 'face_login:top' %}">top</a>
            <a href="{% url 'face_login:list' %}">list表示</a>
            <a href="{% url 'face_login:login' %}">login</a>
            <a href="{% url 'face_login:create'%}">user作成</a>
            {% block header %}
            {% endblock header %}
        </div> -->

        <div class="main">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

research/face_login/templates/face_login/create.html
{% extends 'face_login/base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_p}}
        </table>

        <input type="submit" value="createuser">
    </from>
{% endblock content %}

research/face_login/templates/face_login/index.html
{% extends 'face_login/base.html' %}
{% load static %}

<!-- <!doctype html>
{% load static %}
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>index</title>
  </head>

  <body>
    <h1>index.html</h1>
    <p>{{ welcome }}</p>

  </body>
</html> -->


{% block content %}
    <h1>index.html</h1>


    <ul>
        {% for timedata in login_data %}
            <li>
                person: {{timedata.user}}, time: {{ timedata.time}},  {{timedata.status }}</li>
        {% endfor %}
    </ul>


{% endblock content %}

research/face_login/templates/face_login/list.html
{% extends 'face_login/base.html' %}

<!--
{% block header %}
    <h1>user<h1>
{% endblock header %} -->

{% block content %}
    <h1>Person List</h1>

    <ul>
        {% for person in member_list %}
            <li><a href=" {% url 'face_login:update' person.id %}">
                user id: {{ person.user_id}}, 名前: {{ person.user_name }}</a></li>
        {% endfor %}
    </ul>

{% endblock content %}

research/face_login/templates/face_login/login.html
{% extends 'face_login/base.html' %}

{% block content %}
    <h1<>Login Page</h1>

    <form action="" method="post">
        {% csrf_token %}
        <ul>
            {% for person in member_list %}
                <input type="submit" class="button-1" value="{{ person.user_name }}" name = "{{ person.user_id }}">
            {% endfor %}
        </ul>
        <input type="submit" class="button-1" value="学習" name = "1">
        <input type="submit" class="button-1" value="テスト" name = "3">
    </form>

{% endblock content %}

research/face_login/templates/face_login/loginmoto.html
<!doctype html>
{% load static %}
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>アプリ</title>
  </head>

  <body>
    <h1>login.html</h1>

    <p>{{ result_id }}</p>
    <p>{{ result }}</p>
    <form action = "{% url 'face_login:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type = "submit" name = "authc_button" value ="認証!" class = "formbutton">
    </form>
  </body>
</html>

research/face_login/templates/face_login/person_detail.html
<!doctype html>
{% load static %}
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>app</title>
  </head>

  <body>
    <h1>person_detail.html</h1>
    {{ object.user_name}}
    {{ object.user_id }}
    {{ object.login_data }}
  </body>
</html>

research/face_login/templates/face_login/status.html
{% extends 'face_login/base.html' %}

{% block content %}
    <h1<> Page</h1>

    <form action="" method="post">
        {% csrf_token %}
        <ul>
            {% for person in member_list %}
                <input type="submit" value="{{ person.user_name }}" name ="LOGIN">

            {% endfor %}
        </ul>

        <input type="submit" name = "LOGIN">
    </form>

{% endblock content %}